import json
import os
import subprocess


KYUUBI_REGION = os.environ.get("KYUUBI_REGION", "chnbj")
KYUUBI_WORKSPACE = os.environ.get("KYUUBI_WORKSPACE", "11329")
KYUUBI_CATALOG = os.environ.get("KYUUBI_CATALOG", "iceberg_zjyprc_hadoop")
KYUUBI_ENGINE = os.environ.get("KYUUBI_ENGINE", "presto")


def execute_query(sql: str) -> dict:
    result = subprocess.run(
        ["kyuubi", "sql", "query", sql,
         "--region", KYUUBI_REGION, "--workspace", KYUUBI_WORKSPACE,
         "--catalog", KYUUBI_CATALOG, "--engine", KYUUBI_ENGINE],
        capture_output=True,
        text=True,
        timeout=300,
    )
    if result.returncode != 0:
        return {"error": result.stderr.strip() or f"kyuubi exited with code {result.returncode}"}

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"raw_output": result.stdout.strip()}


TOOL_DEFINITION = {
    "name": "execute_query",
    "description": (
        "Execute a SQL query via Kyuubi against Iceberg tables. "
        "The SQL MUST have been generated by the nl-sql skill — never hand-written. "
        "Only SELECT queries are allowed."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "sql": {
                "type": "string",
                "description": "SQL query generated by nl-sql skill",
            },
        },
        "required": ["sql"],
    },
}


def handle_execute_query(sql: str) -> str:
    sql_upper = sql.strip().upper()
    if not sql_upper.startswith("SELECT") and not sql_upper.startswith("SHOW") and not sql_upper.startswith("DESCRIBE"):
        return json.dumps({"error": "Only SELECT/SHOW/DESCRIBE queries are allowed"})

    result = execute_query(sql)
    return json.dumps(result, ensure_ascii=False, default=str)
