"""add章节状态和日期字段

Revision ID: af1063fe61d5
Revises: 5a7400d5ea1e
Create Date: 2026-05-19 03:44:10.651722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1063fe61d5'
down_revision: Union[str, Sequence[str], None] = '5a7400d5ea1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('chapters', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    op.add_column('chapters', sa.Column('completed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'completed_date')
    op.drop_column('chapters', 'scheduled_date')
    op.drop_column('chapters', 'status')
    # ### end Alembic commands ###
