"""add评论世界观冲突伏笔审阅表

Revision ID: c5f9a55eb8e6
Revises: e1d8d49bec38
Create Date: 2026-05-19 03:59:12.809544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f9a55eb8e6'
down_revision: Union[str, Sequence[str], None] = 'e1d8d49bec38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
