.PHONY: help install backend frontend dev seed test fmt clean pack pack-clean reset-data \
        prod-build prod-run prod

VERSION ?= $(shell date +%Y%m%d)
PKG_NAME = ice-workbench-$(VERSION).zip
# 生产监听端口（ICE_BIND_PORT 环境变量可覆盖；默认 8000）
PROD_PORT ?= $(if $(ICE_BIND_PORT),$(ICE_BIND_PORT),8000)
# 绑定地址：0.0.0.0 让公网 / 局域网可达
PROD_HOST ?= 0.0.0.0

help:
	@echo "ICE Data Workbench v3 — local dev + deploy"
	@echo ""
	@echo "  make install     install backend (pip) + frontend (npm)"
	@echo "  make dev         run backend + frontend in parallel (dev :5173 + :8000)"
	@echo "  make backend     only backend on :8000"
	@echo "  make frontend    only frontend on :5173"
	@echo ""
	@echo "  make prod        build frontend + run single-port server (public-access ready)"
	@echo "  make prod-build  only build frontend dist"
	@echo "  make prod-run    only start backend on \$$PROD_HOST:\$$PROD_PORT (0.0.0.0:8000)"
	@echo ""
	@echo "  make seed        one-shot seed bootstrap"
	@echo "  make test        backend pytest"
	@echo "  make pack        build a portable zip (includes .env, excludes venv/node_modules)"
	@echo "  make pack-clean  pack + delete runtime data first (for clean handoff)"
	@echo "  make reset-data  wipe runtime data (.cache, users/<uid>, tasks/<tid>)"
	@echo "  make clean       remove venv + node_modules + caches"

install:
	cd backend && python3 -m venv .venv && . .venv/bin/activate && pip install -U pip && pip install -e ".[dev]"
	cd frontend && npm install

backend:
	cd backend && . .venv/bin/activate && uvicorn app.main:app --reload --port 8000

frontend:
	cd frontend && npm run dev

dev:
	@echo "Starting backend (8000) + frontend (5173) — Ctrl-C to stop both"
	@(cd backend && . .venv/bin/activate && uvicorn app.main:app --reload --port 8000) & \
	 (cd frontend && npm run dev) ; \
	 wait

prod-build:
	@echo "Building frontend dist…"
	cd frontend && npm run build
	@echo "  ✓ frontend/dist/ ready"

prod-run:
	@echo "Starting backend on $(PROD_HOST):$(PROD_PORT) (single-port, serves SPA + API + WS)"
	cd backend && . .venv/bin/activate && \
	  uvicorn app.main:app --host $(PROD_HOST) --port $(PROD_PORT) --workers 1

prod: prod-build prod-run

seed:
	cd backend && . .venv/bin/activate && python -m app.seed.runner

test:
	cd backend && . .venv/bin/activate && pytest -q

fmt:
	cd backend && . .venv/bin/activate && ruff check --fix app tests || true
	cd frontend && npm run lint -- --fix || true

# Wipe runtime-generated data (safe to re-run; seed re-creates admin on next boot).
reset-data:
	@echo "Removing runtime data (.cache + per-user + per-task)…"
	@rm -rf .cache
	@find users -mindepth 1 -maxdepth 1 -type d ! -name 'README*' -exec rm -rf {} +
	@find tasks -mindepth 1 -maxdepth 1 -type d ! -name 'README*' -exec rm -rf {} +
	@find agents -name 'cards.md' -path '*/prompt/cards.md' -delete 2>/dev/null || true
	@find . -name '*.lock' -path '*/tasks/*' -delete 2>/dev/null || true
	@echo "  done."

clean:
	rm -rf backend/.venv backend/.pytest_cache
	find backend -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	rm -rf frontend/node_modules frontend/dist
	rm -rf .cache

# Build a self-contained zip for handoff. Includes .env and source data;
# excludes anything regenerated by `make install` or runtime.
pack: prod-build
	@command -v zip >/dev/null 2>&1 || { echo "zip not found"; exit 1; }
	@echo "Packing $(PKG_NAME)…"
	@rm -f $(PKG_NAME)
	@zip -r $(PKG_NAME) . \
	  -x '*.git/*' '*.git' \
	  -x '*backend/.venv/*' \
	  -x '*frontend/node_modules/*' \
	  -x '.cache/*' '*/.cache/*' \
	  -x 'users/[a-f0-9]*/*' \
	  -x 'tasks/[a-f0-9]*/*' \
	  -x '*__pycache__/*' \
	  -x '*.pyc' '*.pyo' \
	  -x '*.pytest_cache/*' \
	  -x '*.ruff_cache/*' \
	  -x '*.mypy_cache/*' \
	  -x 'extracted/*' \
	  -x 'ice_data_workspace_v2.zip' \
	  -x '.DS_Store' '*/.DS_Store' \
	  -x '*.log' \
	  -x '*.lock' \
	  -x 'ice-workbench-*.zip' \
	  -x '.tmp-*' \
	  >/dev/null
	@echo ""
	@echo "  ✓ $(PKG_NAME)  ($$(du -h $(PKG_NAME) | cut -f1))"
	@echo ""
	@echo "  Send this single file to the target machine, then on it:"
	@echo "    unzip $(PKG_NAME) -d ice-workbench"
	@echo "    cd ice-workbench"
	@echo "    ./deploy.sh --run"
	@echo ""

pack-clean: reset-data pack
